### ISSUE TITLE
Furious v3 Buttons

### ISSUE THREAD

**Issue by SkeemoFPV** [fncisco/Unishark#1]
On my Furious V3 module I have found the button pins to be as follows.

#ifdef v3
#define BUT1 8 // up
#define BUT2 9 // middle
#define BUT3 10 // down

Also I am finding the module is running much hotter than with stock FW, I know they have supposedly done some things to reduce current draw by dimming screen and leds

**Comment by fncisco** [comment]
Thank you for feedback, I'm cleaning the code and soon will publish the new one.

**Comment by SkeemoFPV** [comment]
Great stuff, looking forward to it.
